### PR TITLE
Ml finalwork

### PR DESCRIPTION
**Pull request by Flogreeni**
Please review again, even if  not all the other feedback is worked in. the main part for the tuning and the evaluation are much better now.
cheers Flo

### CODE REVIEW

**Review by maximilian-hildebrandt — CHANGES_REQUESTED** [review]
See detailed feedback in Slack, evaluation metrics need to be changed.

**Comment by Flogreeni** [comment]
please review again max :)

**Comment by Flogreeni** [comment]
Your dummy classifier still works on the test set. Apply cv on x_train, y_train to get 
an honest performance appraisal. Remove the predictions on the test set in the 
beginning of the model trainings. You only want to do this at the very end.  

**don´t really understand this. but the fitting is just on train dataset and the prediction for evaluation on the test. ** 

o Name your decision tree model meaningfully, "tuning_model" is not self-
explanatory. Better: decision_tree_classifier or similar 

**did not make the renaming yet**

**Review by maximilian-hildebrandt — APPROVED** [review]
The decision tree evaluation needs to be changed (still has a regression metric as metric), rest is looking fine from a first glance. No time for detailled review.

**Review by maximilian-hildebrandt — APPROVED** [review]

**Pull request merged**
